"""empty message

Revision ID: 125734d83b4a
Revises: 
Create Date: 2020-09-17 13:56:34.772039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125734d83b4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('event_table_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_event_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personid', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('vec_low', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('vec_high', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_event_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personid', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('vec_low', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('vec_high', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_event_2')
    op.drop_table('table_event_1')
    op.drop_table('events')
    # ### end Alembic commands ###
